import type { Task } from '../types/task'

// Ensure newly added built-in tasks do NOT retroactively apply to past windows/dates.
// We set this to the local start-of-day for the day Order Report was introduced.
export const ORDER_REPORT_CREATED_AT_MS = new Date(2025, 11, 28, 0, 0, 0, 0).getTime()
// v2.0: Combined Ice (Left+Right) task introduction date (local start-of-day).
export const ICE_COMBINED_CREATED_AT_MS = new Date(2026, 0, 5, 0, 0, 0, 0).getTime()

export const TASKS: Task[] = [
  {
    id: 'break-selection',
    name: 'Break Selection',
    icon: '☕',
    requirements: [
      'Work with your teammate to determine break times.',
      'Fill both slots: employee → lunch/double → break start time.',
      'Breaks must be scheduled between 1:00 PM and 4:00 PM.',
      'Lunch shift = 30 minute break. Double shift = 1 hour break.',
    ],
    windows: ['11'],
    // Planning-only task: do not affect leaderboard points.
    weight: 0,
  },
  {
    id: 'napkins',
    name: 'Napkins',
    icon: '📄',
    requirements: [
      'Refill all napkins at every table.',
      'Fill napkins up to the top at the end of the bar.',
    ],
    windows: ['11'],
  },
  {
    id: 'salt-pepper',
    name: 'Salt and Pepper',
    icon: '🍴',
    requirements: ['Ensure each table has one salt and one pepper.'],
    windows: ['11'],
  },
  {
    id: 'bathroom-check',
    name: 'Bathroom Check',
    icon: '🚻',
    requirements: [
      'Double check both bathrooms.',
      'Ensure cleaning has been fully completed from night shift.',
    ],
    windows: ['11'],
    weight: 1.2,
    askNightShiftComplete: true,
  },
  {
    id: 'sneeze-guard',
    name: 'Sneeze Guard Cleaning',
    icon: '✨',
    requirements: [
      'Wipe the glass at the top of the bar with Windex.',
      'Clean the sides.',
      'Fully remove any leftover residue from the night before.',
    ],
    windows: ['11'],
  },
  {
    id: 'ice-check',
    name: 'Ice Check',
    icon: '❄️',
    requirements: [
      'Ensure ice has been filled in both machines from the night before.',
    ],
    windows: ['11'],
    askNightShiftComplete: true,
  },
  {
    id: 'dining-area',
    name: 'Dining Area Check',
    icon: '🍽',
    requirements: [
      'Take down all chairs.',
      'Ensure all tables have been wiped from the night before.',
      'Check that the cleaning area has been fully cleaned.',
      'Make sure the mat in front of the door is swept.',
      'Ensure forks and spoons are filled.',
    ],
    windows: ['11'],
    weight: 1.2,
  },
  {
    id: 'register-bowl',
    name: 'Register / Bowl Area',
    icon: '💳',
    requirements: [
      'Ensure the register area is clean and presentable for customers.',
      'Ensure the bowl area is clean and presentable for customers.',
    ],
    windows: ['11'],
  },
  {
    id: 'towels',
    name: 'Towels',
    icon: '👕',
    requirements: [
      'Fully rinse out the table towels to remove all bleach.',
      'Replace the towel bucket water.',
    ],
    windows: ['11'],
  },
  {
    id: 'turn-on-music',
    name: 'Turn on the Music',
    icon: '🎵',
    requirements: ['Turn on the music for the day.'],
    windows: ['11'],
  },
  {
    id: 'turn-on-open-sign',
    name: 'Turn On Open Sign',
    // iOS 9: newer emoji may not render; use a plain bullet and color it via CSS.
    icon: '●',
    requirements: [
      'Turn on the OPEN sign at the front.',
      'Confirm it is visible from outside.',
    ],
    windows: ['11'],
  },
  {
    id: 'unlock-door',
    name: 'Unlock the Door',
    icon: '🔓',
    requirements: ['Unlock the front door for opening.'],
    windows: ['11'],
  },
  {
    id: 'bathroom-touchup',
    name: 'Bathroom Touch Up',
    icon: '🚻',
    requirements: [
      'Ensure paper towels and toilet paper remain filled.',
      'Do a quick wipe of both bathrooms.',
      'Ensure no overflow of trash or dirt on the sink, toilet, or floor.',
      'Keep bathrooms clean for evening guests.',
    ],
    windows: ['17'],
    requiresChecklist: 3,
    weight: 1.2,
  },
  {
    id: 'dining-area-5pm',
    name: 'Dining Area Check',
    icon: '🍽',
    requirements: [
      'Ensure all tables and seats are wiped.',
      'Ensure floors are swept.',
      'Make sure mat in front of door is swept.',
    ],
    windows: ['17'],
  },
  {
    id: 'count-drawer',
    name: 'Count Drawer',
    icon: '💵',
    requirements: ['Count the cash drawer.'],
    windows: ['17'],
  },
  {
    id: 'left-ice-5pm',
    name: 'Left Ice',
    icon: '❄️',
    requirements: ['Make sure ice is filled.'],
    windows: ['17'],
    weight: 1.2,
  },
  {
    id: 'right-ice-5pm',
    name: 'Right Ice',
    icon: '❄️',
    requirements: ['Make sure ice is filled.'],
    windows: ['17'],
    weight: 1.2,
  },
  {
    id: 'ice-5pm',
    name: 'Ice (Left + Right)',
    icon: '❄️',
    requirements: ['Fill both ice machines.'],
    windows: ['17'],
    // Combined: Left (1.2) + Right (1.2) = 2.4
    weight: 2.4,
    createdAtMs: ICE_COMBINED_CREATED_AT_MS,
  },
  {
    id: 'towels-5pm',
    name: 'Towels',
    icon: '👕',
    requirements: [
      'Fully rinse out towels.',
      'Replace water.',
    ],
    windows: ['17'],
  },
  {
    id: 'register-bowl-5pm',
    name: 'Register / Bowl Area',
    icon: '💳',
    requirements: [
      'Look around to make sure everything is clean.',
      'Ensure presentable for customers.',
    ],
    windows: ['17'],
  },
  {
    id: 'split-tips',
    name: 'Split Tips',
    icon: '💰',
    requirements: [
      'Take out the tip cash.',
      'Split it amongst each other.',
      'Write down card tips and amount split.',
    ],
    windows: ['17'],
  },
  {
    id: 'food-bar-check',
    name: 'Food Bar Check',
    icon: '🍲',
    requirements: [
      'Ensure all food is clear from the food bar.',
      'Ensure floor is clear before shift change.',
    ],
    windows: ['17'],
  },
  {
    id: 'drink-station-5pm',
    name: 'Drink Station',
    icon: '🍹',
    requirements: [
      'Ensure the drink station is presentable and not dirty.',
      'Ensure cup lids and straws remain full.',
      'Wipe the drink station.',
    ],
    windows: ['17'],
  },
  {
    id: 'utensils',
    name: 'Utensils',
    icon: '🔪',
    requirements: [
      'If necessary, refill forks.',
      'If necessary, refill spoons.',
      'If necessary, refill chopsticks.',
    ],
    windows: ['17'],
  },
  {
    id: 'refill-to-go-area-5pm',
    name: 'Refill To-Go Area',
    icon: '📦',
    requirements: [
      'Make sure the to-go area is stocked and ready for the next rush.',
      'Stock bowl lids.',
      'Stock forks.',
      'Stock spoons.',
      'Stock chopsticks.',
      'Stock soy sauce.',
      'Stock plastic bags.',
    ],
    windows: ['17'],
  },
  {
    id: 'bowl-refill',
    name: 'Bowl Refill',
    icon: '🍜',
    requirements: [
      'Refill bowls.',
      'Refill trays.',
      'Refill cups.',
    ],
    windows: ['17'],
  },
  {
    id: 'blue-bag-count',
    name: '5:00 Blue Bag Count',
    icon: '💼',
    requirements: ['Count the blue bag to verify $700.'],
    windows: ['17'],
  },
  {
    id: 'order-report-5pm',
    name: 'Order Report',
    icon: '🧾',
    requirements: ['Report the number of orders taken by each employee (as shown in KwickPOS UserReport).'],
    windows: ['17'],
    weight: 1.8,
    createdAtMs: ORDER_REPORT_CREATED_AT_MS,
  },
  {
    id: 'clean-bathrooms-close',
    name: 'Clean Bathrooms',
    icon: '🚻',
    requirements: [
      'Wipe mirrors with Windex.',
      'Clean sink.',
      'Use broom to push down trash (if trash is full it must be taken out).',
      'Clean toilet inside and top.',
      'Sweep floors.',
      'Fill soap, paper towels, and toilet paper.',
    ],
    windows: ['21'],
    requiresChecklist: 6,
    weight: 1.2,
  },
  {
    id: 'wipe-tables-close',
    name: 'Wipe All Tables',
    icon: '🍽',
    requirements: ['Wipe all tables.'],
    windows: ['21'],
  },
  {
    id: 'chairs-up',
    name: 'Put Chairs on Top of Tables',
    icon: '⬆️',
    requirements: ['Put chairs on top of tables.'],
    windows: ['21'],
  },
  {
    id: 'sweep-close',
    name: 'Sweep',
    icon: '💨',
    requirements: ['Sweep main floor and line area.', 'Dispose in back.'],
    windows: ['21'],
  },
  {
    id: 'mop-close',
    name: 'Mop',
    icon: '💧',
    requirements: [
      'Mop high-traffic areas.',
      'Put out wet-floor sign.',
    ],
    windows: ['21'],
    weight: 1.2,
  },
  {
    id: 'take-out-trash',
    name: 'Take Out Trash',
    icon: '🗑️',
    requirements: [
      'Take out trash in dining area.',
      'Take out trash from bar and bowl areas.',
      'Check the bathroom trash to see if it needs to be taken out.',
    ],
    windows: ['21'],
  },
  {
    id: 'wipe-table-numbers',
    name: 'Wipe Off Table Numbers',
    icon: '🔢',
    requirements: [
      'Ensure all table numbers are clean for the next customers.',
    ],
    windows: ['17', '21'],
  },
  {
    id: 'empty-dust-pan',
    name: 'Empty Dust Pan',
    icon: '🗑️',
    requirements: [
      'Empty the dust pan.',
    ],
    windows: ['17', '21'],
  },
  {
    id: 'towels-close',
    name: 'Towels',
    icon: '👕',
    requirements: ['Follow labeled instructions above towel bucket to presoak overnight.'],
    windows: ['21'],
  },
  {
    id: 'night-count-drawer',
    name: 'Night Count Drawer',
    icon: '💵',
    requirements: ['Count the cash drawer.'],
    windows: ['21'],
  },
  {
    id: 'split-tips-close',
    name: 'Split Tips',
    icon: '💰',
    requirements: [
      'Take out the tip cash.',
      'Split it amongst each other.',
      'Write down card tips and amount split.',
    ],
    windows: ['21'],
  },
  {
    id: 'left-ice-close',
    name: 'Left Ice',
    icon: '❄️',
    requirements: ['Make sure ice is filled.'],
    windows: ['21'],
    weight: 1.2,
  },
  {
    id: 'right-ice-close',
    name: 'Right Ice',
    icon: '❄️',
    requirements: ['Make sure ice is filled.'],
    windows: ['21'],
    weight: 1.2,
  },
  {
    id: 'ice-close',
    name: 'Ice (Left + Right)',
    icon: '❄️',
    requirements: ['Fill both ice machines.'],
    windows: ['21'],
    // Combined: Left (1.2) + Right (1.2) = 2.4
    weight: 2.4,
    createdAtMs: ICE_COMBINED_CREATED_AT_MS,
  },
  {
    id: 'utensils-close',
    name: 'Utensils',
    icon: '🔪',
    requirements: [
      'If necessary, refill forks.',
      'If necessary, refill spoons.',
      'If necessary, refill chopsticks.',
    ],
    windows: ['21'],
  },
  {
    id: 'refill-to-go-area-close',
    name: 'Refill To-Go Area',
    icon: '📦',
    requirements: [
      'Make sure the to-go area is stocked and ready for the next rush.',
      'Stock bowl lids.',
      'Stock forks.',
      'Stock spoons.',
      'Stock chopsticks.',
      'Stock soy sauce.',
      'Stock plastic bags.',
    ],
    windows: ['21'],
  },
  {
    id: 'bowl-refill-close',
    name: 'Bowl Refill',
    icon: '🍜',
    requirements: [
      'Refill bowls.',
      'Refill trays.',
      'Refill cups.',
    ],
    windows: ['21'],
  },
  {
    id: 'blue-bag-count-close',
    name: 'Blue Bag Count',
    icon: '💼',
    requirements: ['Count the blue bag to verify $700.'],
    windows: ['21'],
  },
  {
    id: 'order-report-close',
    name: 'Order Report',
    icon: '🧾',
    requirements: ['Report the number of orders taken by each employee (as shown in KwickPOS UserReport).'],
    windows: ['21'],
    weight: 1.8,
    createdAtMs: ORDER_REPORT_CREATED_AT_MS,
  },
  {
    id: 'lock-door',
    name: 'LOCK DOOR',
    icon: '🔒',
    requirements: ['Lock the front door.'],
    windows: ['21'],
  },
  {
    id: 'yum-yum-close',
    name: 'Yum Yum Sauce',
    icon: '🍶',
    requirements: ['Ensure at least all 4 containers of yum yum sauce are full.'],
    windows: ['17', '21'],
  },
  {
    id: 'peanuts-noodles-close',
    name: 'Peanuts Crispy Noodles',
    icon: '🍝',
    requirements: [
      'If running low, refill peanuts.',
      'If running low, refill crispy noodles.',
    ],
    windows: ['21'],
  },
  {
    id: 'seasoning-close',
    name: 'Seasoning',
    icon: '🌶',
    requirements: ['Ensure all seasonings are filled for the night.'],
    windows: ['21'],
  },
  {
    id: 'drink-station-close',
    name: 'Drink Station',
    icon: '🍹',
    requirements: [
      'Ensure the drink station is presentable and not dirty.',
      'Wipe the drink station.',
      'Refill cup lids and straws.',
    ],
    windows: ['21'],
  },
  {
    id: 'fridge-check',
    name: 'Fridge Check',
    icon: '❄️',
    requirements: ['Make sure the fridge is presentable for the morning shift.'],
    windows: ['21'],
  },
]
